name: shoe_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  easy_stepper: ^0.7.3
  get_storage: ^2.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

